name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_patter: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
            
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{ steps.version.outputs.version }}
        
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION"
        echo "Fin del login"
            
  #  - name: Build the Docker image
  #    run: |
  #      docker build -t janazcopazos/docker-graphql:0.0.2 .
  #      docker build -t janazcopazos/docker-graphql:latest .
  #
  #  - name: Push Docker image
  #    run: |
  #      docker push janazcopazos/docker-graphql:0.0.2
  #      docker push janazcopazos/docker-graphql:latest

        
